version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DJANGO_DEBUG=${DJANGO_DEBUG}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - WEB_PORT=${WEB_PORT}
    command: gunicorn polygon_project.wsgi:application --bind 0.0.0.0:${WEB_PORT}
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - STATIC_URL=${STATIC_URL}
      - MEDIA_URL=${MEDIA_URL}
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./polygon_project/nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - web

  pgadmin:
    build:
      context: .
      dockerfile: docker/pgadmin/Dockerfile
      args:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: